"""Provider-independent domain model for Maestro."""

from maestro.domain.exceptions import (
    MaestroDomainError,
    ResourceAlreadyExistsError,
    ResourceConflictError,
    ResourceNameNotFoundError,
    ResourceNotFoundError,
)
from maestro.domain.projects import (
    AgentReference,
    DependencyChangePolicy,
    KnowledgeSourceReference,
    Project,
    ProjectPhase,
    ProjectPolicy,
    ProjectRepository,
    ProjectRepositoryBinding,
    ProjectRepositoryStatus,
    ProjectRoleBinding,
    ProjectSpec,
    ProjectStatus,
    RepositoryType,
    WorkflowReference,
)
from maestro.domain.repositories import (
    ResourceRepository,
    ResourceSelector,
    apply_deletion_mark,
    apply_spec_update,
    apply_status_update,
    ensure_expected_resource_version,
    validate_resource_snapshot,
)
from maestro.domain.resources import (
    API_VERSION,
    BaseResource,
    Condition,
    ConditionStatus,
    Metadata,
    OwnerReference,
    ResourceReference,
    Spec,
    Status,
)

__all__ = [
    "API_VERSION",
    "AgentReference",
    "BaseResource",
    "Condition",
    "ConditionStatus",
    "DependencyChangePolicy",
    "KnowledgeSourceReference",
    "MaestroDomainError",
    "Metadata",
    "OwnerReference",
    "Project",
    "ProjectPhase",
    "ProjectPolicy",
    "ProjectRepository",
    "ProjectRepositoryBinding",
    "ProjectRepositoryStatus",
    "ProjectRoleBinding",
    "ProjectSpec",
    "ProjectStatus",
    "RepositoryType",
    "ResourceAlreadyExistsError",
    "ResourceConflictError",
    "ResourceNameNotFoundError",
    "ResourceNotFoundError",
    "ResourceReference",
    "ResourceRepository",
    "ResourceSelector",
    "Spec",
    "Status",
    "WorkflowReference",
    "apply_deletion_mark",
    "apply_spec_update",
    "apply_status_update",
    "ensure_expected_resource_version",
    "validate_resource_snapshot",
]
